### ISSUE TITLE
Añadir Dockerfile

### ISSUE THREAD

**Issue by ssaavedra** [gpul-labs/labs-landing#7]
Necesitamos un Dockerfile para poder facer deploy das novas versións desta páxina cando migremos ao servidor novo (i.e., a idea é que esta web sexa un container HTML estático).

Podemos utilizar como imaxes base mesmo nginx; deberían de ser só catro liñas ou así.

Se teño un oco despois fágoo, pero senón, @frantsao ? ;-)

En canto estea podemos subilo ao Docker Hub (e configuralo automáticamente no servidor para que se actualice só, con [watchtower](https://github.com/CenturyLinkLabs/watchtower)).

**Comment by frantsao** [comment]
He finalizado mi primera semana de curro con un trancazo... pero si consigo despejarme, me pongo a ello...

**Comment by ssaavedra** [comment]
Debería de estar xa dispoñible en https://hub.docker.com/r/gpul/labs-landing/ e configurado o webhook para que se pushee a imaxe ao Docker Hub en canto se actualice.
